import { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Quiz.module.scss"

const Quiz: NextPage = () => {
    return(
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.background}></div>
            <div className={styles.mainContainer}>
                <div className={styles.header}>
                    <div className={styles.col1}></div>
                    <div className={styles.col2}>
                        <div className={styles.line1}></div>
                        <div className={styles.line2}></div>
                    </div>
                    <div className={styles.col3}></div>
                </div>
                <div className={styles.middle}>
                    <div className={styles.gameInfo}>
                        <div className={styles.champCounter}>
                            <div className={styles.text}>ROUND</div>
                            <div className={styles.value}>2</div>
                        </div>
                        <div className={styles.timer}>
                            <div className={styles.text}>TIMER</div>
                            <div className={styles.value}>04:25</div>
                        </div>
                        <div className={styles.difficulty}>
                            <div className={styles.text}>GAME DIFFICULTY</div>
                            <div className={styles.value}>CLASSIC</div>
                        </div>
                    </div>
                    <div className={styles.championSelect}>
                        <div className={styles.goBack}></div>
                        <div className={styles.currentChampion}>
                            <div className={styles.circle}></div>
                        </div>
                        <div className={styles.goNext}></div>
                    </div>
                    <div className={styles.askChampion}>
                        <div className={styles.button}></div>
                        <div className={styles.button}></div>
                        <input type="text" className={styles.championInput} />
                        <div className={styles.button}>
                            <div className={styles.text}>Aide</div>
                            <div className={styles.value}>
                                +15s
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.footer}>
                    <div className={styles.championPannel}>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>
                        <div className={styles.championCase}></div>

                    </div>
                </div>
            </div>
        </div>
    )
}

export default Quiz;