import { NextPage } from "next";
import Head from "next/document";
import styles from "../styles/Quiz.module.scss"

const Quiz: NextPage = () => {
    return(
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="mainContainer">
                    <div className="header"></div>
                    <div className="middle">
                        <div className="askChampion">
                            <input type="text"/>
                        </div>
                    </div>
                    <div className="footer">
                        <div className="championPannel">
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>
                            <div className="championCase"></div>

                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Quiz;